#ifndef API_H
#define API_H

#define DELIMITER "/"
#define DATE_FORMAT "yyyy-MM-dd"
#define DATETIME_FORMAT "yyyy-MM-dd hh:mm:ss"

//Контроллеры
#define CTRL_LOGIN "login"
#define CTRL_USER_TYPE_TABLE "userType"
#define CTRL_USER_TABLE "user"
#define CTRL_CITY_TABLE "city"
#define CTRL_REGION_TABLE "region"
#define CTRL_CONTACT_PERSON_TABLE "contact_person"
#define CTRL_CASE_TABLE "case"
#define CTRL_USER_LESSON_TABLE "user_lesson"
#define CTRL_USER_ACHIEVEMENT_TABLE "user_achievement"
#define CTRL_ACHIEVEMENT_TABLE "achievement"
#define CTRL_ACHIEVEMENT_TREE "achievementTree"
#define CTRL_LESSON_TABLE "lesson"
#define CTRL_CASE_UNIT_TABLE "case_unit"
#define CTRL_TASK_TABLE "task"
#define CTRL_QUANTUM_TABLE "quantum"
#define CTRL_ACHIEVEMENT_CHILDREN_TABLE "achievement_children"
#define CTRL_ACHIEVEMENT_GROUP_TABLE "achievement_group"
#define CTRL_LEARNING_GROUP_TABLE "learning_group"
#define CTRL_NOTICE_TYPE_TABLE "notice_type"
#define CTRL_TIMING_GRID_TABLE "timing_grid"


#define CTRL_REPORTS "report"
#define CTRL_ATTACHMENTS "attachments"
#define CTRL_NOTIFICATIONS "notification"
#define CTRL_MESSAGES "message"
#define CTRL_ADMIN_ACTION "adminAction"
#define CTRL_TEACHER_ACTION "teacherAction"
#define CTRL_STUDENT_ACTION "studentAction"
#define CTRL_STUDENT_INFO "studentInfo"
#define CTRL_TEACHER_INFO "teacherInfo"
#define CTRL_CASE_ACHIEVEMENT "case_achievement"
#define CTRL_CASE_REQUIREED_ACHIEVEMENT "case_required_achievement"
#define CTRL_LEARNING_GROUP_HOURS "learning_group_hours"
#define CTRL_REQUIRED_ACHIEVEMENT_GROUP "required_achievement_group"
#define CTRL_USER_CASE "user_case"
#define CTRL_USER_LEARNING_GROUP "user_learning_group"
#define CTRL_LEARNING_GROUP_CASE "learning_group_case"
#define CTRL_USER_TASK "user_task"

#define CTRL_QUANTUM_BY_USER "quantumByUser"
#define CTRL_TIMING_GRID_UNIT "timing_grid_unit"
#define CTRL_ADMIN_SCHEDULE "adminSchedule"
#define CTRL_ACTION_LOG "action_log"


//Действия
#define ACT_UNREGISTER_FROM_COURSE "unregisterFromCourse"
#define ACT_UNREGISTER_FROM_SKILL "unregisterFromLessonCourse"
#define ACT_DELETE_TASK_SCORE "deleteTaskScore"
#define ACT_DELETE_LESSON_SCORE "deleteLessonScore"
#define ACT_UPDATE_TASK_SCORE "updateTaskScore"
#define ACT_UPDATE_LESSON_SCORE "updateLessonScore"
#define ACT_REGISTER_LESSON_SCORE "registerLessonScore"
#define ACT_REGISTER_TASK_SCORE "registerTaskScore"
#define ACT_REGISTER_LESSON "registerLesson"
#define ACT_UNREGISTER_LESSON "unregisterLesson"
#define ACT_STUDENT_SUMMARY "studentSummary"
#define ACT_CLONE_CASE "cloneCase"
#define ACT_ASSIGN_USER_CASE "assignUserCase"
#define ACT_DELETE_USER_CASE "deleteUserCase"
#define ACT_REGISTER_USER_FOR_LEARNING_GROUP "registerUserForLearningGroup"
#define ACT_UNREGISTER_USER_FROM_LEARNING_GROUP "unregisterUserFromLearningGroup"
#define ACT_ACTIVATE_CASE "activateCase"
#define ACT_DEACTIVATE_CASE "deactivateCase"
#define ACT_REMOVE_REQUIRED_CASE_ACHIEVEMENTS "removeRequiredCaseAchievements"

#define ACT_GET_NOTIFICATIONS "getNotifications"
#define ACT_CHECK_VIEWED "checkViewed"
#define ACT_SEND_MESSAGE "sendMessage"

//Колонки и параметры
#define PRM_ID "id"
#define PRM_NAME "name"
#define PRM_DESCRIPTION "description"
#define PRM_USERNAME "username"
#define PRM_PASSWORD "pswd"
#define PRM_FIRST_NAME "first_name"
#define PRM_LAST_NAME "last_name"
#define PRM_SECOND_NAME "second_name"
#define PRM_BIRTH_DATE "birth_date"
#define PRM_GENDER "gender"
#define PRM_CREATED "created"
#define PRM_LAST_LOGIN "last_login"
#define PRM_ACTIVE "active"
#define PRM_CITY_ID "city_id"
#define PRM_SYSUSER_TYPE_ID "sysuser_type_id"
#define PRM_MAX_COURSE_COUNT "max_course_count"
#define PRM_SPECIALITY "speciality"
#define PRM_PHONE "phone"
#define PRM_ACTUAL_ADDRESS "actual_address"
#define PRM_PASSPORT_NUMBER "passport_number"
#define PRM_PASSPORT_SERIES "passport_series"
#define PRM_PASSPORT_ISSUE_DATE "passport_issue_date"
#define PRM_PASSPORT_ISSUE_AUTHORITY "passport_issue_authority"
#define PRM_PASSPORT_ADDRESS "passport_address"
#define PRM_PASSPORT_DEPARTMENT_CODE "passport_department_code"
#define PRM_PERSONNEL_NUMBER "personnel_number"
#define PRM_STAFFER "staffer"
#define PRM_SHIFT "shift"
#define PRM_BALANCE "balance"
#define PRM_SYSUSER_TYPE "sysuser_type"
#define PRM_PARTNAME "partname"
#define PRM_FULLNAME "fullname"
#define PRM_REGION_ID "region_id"
#define PRM_TIMEZONE "timezone"

#define PRM_LOCKED "locked"
#define PRM_FINISHED "finished"
#define PRM_USER_ID "user_id"
#define PRM_CASE_ID "case_id"
#define PRM_LEARNING_GROUP_ID "learning_group_id"

#define PRM_ICON "icon"
#define PRM_LESSON_ID "lesson_id"
#define PRM_LESSON_COURSE_ID "lesson_course_id"
#define PRM_SKILL_UNIT_ID "skill_unit_id"
#define PRM_LESSON_DATE "lesson_date"
#define PRM_LESSON_TIME "lesson_time"
#define PRM_LESSON_SCORE "lesson_score"
#define PRM_TASK_ID "task_id"
#define PRM_FINISH_DATE "finish_date"
#define PRM_SCORE "score"
#define PRM_MAX_SCORE "max_score"
#define PRM_MAX_TASK_SCORE "max_task_score"
#define PRM_SORT_ID "sort_id"
#define PRM_TASK_COUNT "task_count"
#define PRM_START_DATE "start_date"
#define PRM_TEACHER_ID "teacher_id"
#define PRM_STUDENTS_LIMIT "students_limit"
#define PRM_BEGIN_TIME "begin_time"
#define PRM_END_TIME "end_time"
#define PRM_HOUR_NUMBER "hour_number"
#define PRM_CITY_DEFAULT "city_default"
#define PRM_DURATION "duration"
#define PRM_STATUS "status"
#define PRM_DAY_TYPE "day_type"
#define PRM_DAY_OF_WEEK "day_of_week"
#define PRM_ORDER_NUM "order_num"
#define PRM_TIMING_GRID_ID "timing_grid_id"
#define PRM_MENTOR_ID "mentor_id"
#define PRM_COMPLETED "completed"
#define PRM_KNOWLEDGE_OK "knowledge_ok"
#define PRM_AGE_OK "age_ok"
#define PRM_TASK_SCORE "task_score"
#define PRM_PARENTS "parents"
#define PRM_READY "ready"
#define PRM_IN_STUDY "in_study"
#define PRM_TOTAL_MAX_SCORE "total_max_score"
#define PRM_UNIT_COUNT "unit_count"
#define PRM_MIN_PERCENTAGE "min_percentage"
#define PRM_COURSE_COUNT "course_count"
#define PRM_MIN_AGE "min_age"
#define PRM_QUANTUM_ID "quantum_id"
#define PRM_MAX_LESSON_SCORE "max_lesson_score"
#define PRM_HAS_SCORE "has_score"
#define PRM_IS_HOLIDAY "isHoliday"
#define PRM_LAST_ID "last_id"
#define PRM_CLASS_NAME "class"
#define PRM_PATTERN "pattern"
#define PRM_MESSAGE "message"
#define PRM_DATE "date"

//Виртуальные папки присоединяемых файлов
#define VIRT_FOLDER_USER "sysuser"
#define VIRT_FOLDER_SKILL_UNIT "skillunit"
#define VIRT_FOLDER_LESSON "lesson"
#define VIRT_FOLDER_TASK "task"







#endif // API_H
